export const ADD_ITEM_TO_CART = 'ADD_ITEM_TO_CART'
export const REMOVE_ITEM_FROM_CART = 'REMOVE_ITEM_FROM_CART'

export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE'

export const TOGGLE_TOPPINGS = 'TOGGLE_TOPPINGS'
export const UPDATE_PIZZA_SIZE = 'UPDATE_PIZZA_SIZE'
export const RESET_FORM = 'RESET_FORM'
